print("-------------------------")
print("--                     --")
print("--                     --")
print("--- test py program    --")
print("--                     --")
print("--                     --")
print("-------------------------")
